version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: "server"
    ports:
      - "5000:5000"
    networks:
      - appnet
    stdin_open: true
    tty: true

  client1:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: "client1"
    depends_on:
      - server
    networks:
      - appnet
    volumes:
      - ./client_data:/app/client_data
    stdin_open: true
    tty: true

  client2:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: "client2"
    depends_on:
      - server
    networks:
      - appnet
    volumes:
      - ./client_data:/app/client_data
    stdin_open: true
    tty: true

networks:
  appnet:
